version: "3"

services:
  db:
    image: postgis/postgis:13-master
    environment:
      - POSTGRES_DB=counterfactualcovid
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    expose:
      - "5432"
    restart: always
  backend:
    build: ./backend
    image: itscares.azurecr.io/cfcov-backend:v1
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.docker
    links:
      - db:db
    expose:
      - "8000"
    restart: always
  frontend:
    build: ./frontend
    image: itscares.azurecr.io/cfcov-frontend:v1
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always
