# Generated by Django 3.1.5 on 2021-01-26 13:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("countries", "0001_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="PossibleDates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_days_first_restrictions", models.PositiveIntegerField()),
                ("n_days_lockdown", models.PositiveIntegerField()),
                ("dates_counterfactual_first_restrictions", models.DateField()),
                ("dates_counterfactual_lockdown", models.DateField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="possibledates",
                        to="countries.country",
                    ),
                ),
            ],
        )
    ]
