# Generated by Django 3.1.5 on 2021-03-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("countries", "0001_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="PossibleDates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_days_first_restrictions", models.FloatField(null=True)),
                ("n_days_lockdown", models.FloatField(null=True)),
                (
                    "dates_counterfactual_first_restrictions",
                    models.DateField(null=True),
                ),
                ("dates_counterfactual_lockdown", models.DateField(null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PossibleDates",
                        to="countries.country",
                    ),
                ),
            ],
        ),
    ]
