# Generated by Django 3.1.5 on 2021-03-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("countries", "0001_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnotPoints",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("knot_date_1", models.DateField(null=True)),
                ("knot_date_2", models.DateField(null=True)),
                ("n_knots", models.IntegerField()),
                ("growth_factor_0_1", models.FloatField(null=True)),
                ("growth_factor_1_2", models.FloatField(null=True)),
                ("growth_factor_2_3", models.FloatField(null=True)),
                ("weight", models.IntegerField(null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="KnotPoints",
                        to="countries.country",
                    ),
                ),
            ],
        ),
    ]
