# Generated by Django 3.1.5 on 2021-01-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSeriesCases",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iso_code", models.CharField(max_length=3)),
                ("date", models.DateField()),
                ("daily_cases", models.FloatField()),
                ("daily_cum_cases", models.FloatField()),
            ],
        ),
    ]
